version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      node-packages:
        patterns:
          - "@types/node"
          - "node"
        update-types:
          - "patch"
          - "minor"
