name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml

  lint:
    needs: install-dependencies
    uses: ./.github/workflows/lint.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  build:
    needs: install-dependencies
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  test:
    needs: install-dependencies
    uses: ./.github/workflows/test.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}

  e2e:
    needs: install-dependencies
    uses: ./.github/workflows/e2e.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
