name: End to End Tests
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ inputs.cache-key }}

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          supabase start --debug
          sleep 10
          npx supabase status --output env > .env.local
          cat .env.local
          source .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=$API_URL" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY" >> $GITHUB_ENV
          echo "SUPABASE_URL=$API_URL" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY" >> $GITHUB_ENV
          echo "SUPABASE_INBUCKET_URL=$INBUCKET_URL" >> $GITHUB_ENV

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright dependencies
        run: |
          npx playwright install --with-deps

      - name: Run e2e tests
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.NEXT_PUBLIC_SUPABASE_URL}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          SUPABASE_URL: ${{ env.SUPABASE_URL}}
          SUPABASE_SERVICE_ROLE_KEY: ${{ env.SUPABASE_SERVICE_ROLE_KEY}}
          SUPABASE_INBUCKET_URL: ${{ env.SUPABASE_INBUCKET_URL}}
          NEXT_PUBLIC_COMPANY_NAME: Test Company
        run: |
          npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_id }}
          path: playwright-report/
          retention-days: 30
